import { Request, Response, NextFunction, RequestHandler } from "express";
import { requestContext } from "../utils/requestContext.js";
import { v4 as uuid } from "uuid";
import logger from "../utils/logger.js";

export const requestContextMiddleware: RequestHandler = (
  req: Request,
  res: Response,
  next: NextFunction,
) => {
  // 1. READ the X-Request-ID set by Nginx (header names are lowercased)
  const nginxRequestIdHeader = req.headers["x-request-id"];
  const nginxRequestId = Array.isArray(nginxRequestIdHeader)
    ? nginxRequestIdHeader[0]
    : nginxRequestIdHeader || undefined;

  // 2. Fallback: If Nginx didn't set it (e.g., direct access), generate one
  const requestId: string = nginxRequestId ?? uuid();

  // 3. Create the context object
  const ctx = { requestId: requestId };

  // 4. Run the request within the async context
  requestContext.run(ctx, () => {
    req.requestId = ctx.requestId;

    // 5. Log the status
    if (!nginxRequestId) {
      logger.warn(
        `[SECURITY ALERT/TRACE] Direct access detected! Request ID generated by Node.js: ${requestId}. Original Source IP: ${req.ip}`,
      );
    } else {
      logger.info(`[TRACE] Request ID from Nginx: ${requestId}`);
    }

    next();
  });
};
